version: 2

jobs:
  build:
    docker:
      - image: circleci/node:lts

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Run tests
          command: npm test

      - run:
          name: Check types
          command: npm run check-types
          when: always

      - run:
          name: Check lint
          command: npm run lint
          when: always

      - run:
          name: Check that schema are up to date
          command: ./node_modules/.bin/1schema check
          when: always

      - run:
          name: Check prettier
          command: npm run prettier:check
          when: always

      - run:
          name: Run the build
          command: npm run build
          when: always
